### PR TITLE
Apple Clone Page Project - Main Page completed.

### PR DESCRIPTION
**Pull request by SlowKingV**
>The project consisted in cloning [this old version of the Apple webpage](https://web.archive.org/web/20140301004610/http://www.apple.com/).

- [x] **main page** structured and stylised
- [x] **index.html** file validated with [W3C Markup Validation Service](https://validator.w3.org/)
- [x] linter issues fixed.

Awaiting validation for merging.

### CODE REVIEW

**Comment by izaiasneto4** [comment]
#### Hi @SlowKingV. There is something that you need to add before getting your project reviewed. :arrow_down: 

- [x] Add a meaningful title and short summary for your Pul Request

If you want to research and have a reference, [here's a link to the requirements and examples](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). When finished with this, please submit the project for the review. Thanks :+1: 

TSE: Izaias Neto

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hey man! Fantastic work, this is looking really tasty :smiley:

I love how much attention you paid to each element, keep this energy through all your projects. There are a few things you need to do so we can merge this beauty and you can move on to the next project, please see them below :eyes:.

#### Validations
Please use this [validator](https://validator.w3.org) to do a quick check on your markup and resolve any resulting errors.

#### Design
The positioning and sizing of elements as well as your font choices are all exquisite, however, please attend to the following:
* Your page currently scrolls horizontally for some reason, please look into the reason why.

## Summary
You've done such a nice job @SlowKingV :rocket:, it was exciting to see such a great job. Your code is tidy, your readme file is shining, wow! Please look into the few things I've listed above and you will be merging in no time :smile:.

If you need any help, please reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilareolusakin). Even if you don't need the help currently, feel free to reach out concerning future projects. I am always happy to discuss code or just chat :+1:.

**Comment by SlowKingV** [comment]
Hi @Oluwadamilareolusakin I already finished the changes but can't ask for a new code review, it says I already have another one in progress.

**Review by MauricioRobayo — APPROVED** [review]
Well done implementing the requested changes. Looking good 🚀 .

Please continue with the next project, this one is **approved**.

**Status**: Approve.

**Pull request merged**
